- hosts: all
  tasks:
     - name: stop containers
       shell: docker container  stop website3
     - name: remove containers
       shell: docker container rm website3
     - name: docker image removal 
       shell: docker rmi -f futumans/webapp2
     - name: create new container
       shell: docker run -itd --name website3 -p 9000:80 futumans/webapp2