- hosts: all
  tasks:
     - name: delete old container
       shell: docker rm -f $(docker ps -aq)
     - name: create new container
       shell: docker run -itd --name dockeransible -p 9000:80 futumans/webpro